"""Add UniqueConstraint to Reminder

Revision ID: 81663f7b9d65
Revises: 46a862720691
Create Date: 2026-09-03 21:49:41.458381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81663f7b9d65'
down_revision: Union[str, Sequence[str], None] = '46a862720691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders') as batch_op:
        batch_op.create_unique_constraint('uq_record_days_before', ['financial_record_id', 'days_before'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders') as batch_op:
        batch_op.drop_constraint('uq_record_days_before', type_='unique')
    # ### end Alembic commands ###
